name: Build and Run .NET 9.0

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Update dependencies
        run: |
          dotnet add EasyCLI/EasyCLI.csproj package System.Text.Json --version 8.0.0
          dotnet add EasyCLI/EasyCLI.csproj package Spectre.Console --version 0.49.1
          dotnet add EasyLib/EasyLib.csproj package Spectre.Console --version 0.49.1
          dotnet restore --force

      - name: Build the project
        run: dotnet build 
        working-directory: EasyCLI

      - name: Run the project
        run: dotnet run 
        working-directory: EasyCLI
